#include "udf.h"

/* Total heat generated by the battery pack (W) */
#define BATTERY_HEAT_POWER 500.0
/* Physical volume of the battery region (m^3) */
#define BATTERY_VOLUME     0.05

/*
 * UDF that provides a constant volumetric heat source
 * for the battery region. Adjust BATTERY_HEAT_POWER
 * and BATTERY_VOLUME to match your model.
 */
DEFINE_SOURCE(battery_heat_source, cell, thread, dS, eqn)
{
    real source;

    /* compute volumetric heat generation (W/m^3) */
    source = BATTERY_HEAT_POWER / BATTERY_VOLUME;

    dS[eqn] = 0.0; /* derivative of source term w.r.t. the variable */
    return source;
}
